# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CartAList' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for CartAList
  pod 'GoogleSignIn', '~> 4.4.0'

 

  pod 'react-native-fbsdk', :path => '../node_modules/react-native-fbsdk'

  target 'CartAListTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'CartAList-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for CartAList-tvOS

  target 'CartAList-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
